[workspace.package]
authors = ["Algorealm"]
edition = "2021"
repository = "https://github.com/algorealmInc/SwarmNL.git"
license = "Apache 2.0"

[workspace]
resolver = "2"

members = [
    "library",
    "guides",
]
