[package]
name = "swarm_nl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ini = "1.3.0"
thiserror = "1.0.58"
rand = "0.8.5"
libp2p = { version="0.53.2", "features"=["ping"] }
libp2p-identity = { version="0.2.8", "features"=["secp256k1", "ecdsa", "rsa"] }