name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests on async-std-runtime
      run: cargo test --features=async-std-runtime
    - name: Run tests on tokio-runtime
      run: cargo test --features=tokio-runtime
