name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # - name: Build with async-std-runtime
      # run: cd swarm_nl && cargo build --features=async-std-runtime
    - name: Build with tokio-runtime
      run: cd swarm_nl && cargo build --features=tokio-runtime
    - name: Run tests
      run: cd swarm_nl && cargo test --features=tokio-runtime
